[package]
name = "zoos-runner-realesrgan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
autobins = false

[[bin]]
name = "zoos-runner-realesrgan-bin"
path = "src/main.rs"

[dependencies]
image.workspace = true
libc.workspace = true
serde_json.workspace = true
sha2.workspace = true
zoos-runner-protocol = { path = "../zoos-runner-protocol" }

[dev-dependencies]
image.workspace = true
serde.workspace = true
tempfile = "=3.27.0"
tokio.workspace = true
zoos-core = { path = "../zoos-core" }
