[package]
name = "zoos-upscale-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "zoos_upscale_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "zoos-upscale"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
serde.workspace = true
tauri = { version = "=2.11.5", features = [] }
tauri-plugin-single-instance = "=2.4.3"
zoos-core = { path = "../crates/zoos-core" }
