[package]
name = "zoos-runner-fake"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde_json.workspace = true
zoos-runner-protocol = { path = "../zoos-runner-protocol" }

[dev-dependencies]
tempfile = "=3.27.0"
