[package]
name = "zoos-runner-ort"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
autobins = false

[[bin]]
name = "zoos-runner-ort-bin"
path = "src/main.rs"

[dependencies]
image.workspace = true
libc.workspace = true
ort.workspace = true
serde_json.workspace = true
sha2.workspace = true
zoos-runner-protocol = { path = "../zoos-runner-protocol" }

[dev-dependencies]
tempfile = "=3.27.0"
